Document: yavdr-test
Title: Debian yavdr-test Manual
Author: <insert document author here>
Abstract: This manual describes what yavdr-test is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yavdr-test/yavdr-test.sgml.gz

Format: postscript
Files: /usr/share/doc/yavdr-test/yavdr-test.ps.gz

Format: text
Files: /usr/share/doc/yavdr-test/yavdr-test.text.gz

Format: HTML
Index: /usr/share/doc/yavdr-test/html/index.html
Files: /usr/share/doc/yavdr-test/html/*.html
